
import { ControlsPage } from "controls_page.slint";
import { TableViewPage, TableViewPageAdapter } from "table_view_page.slint";
import {PlotterPage ,PlotterPageAdapter,PlotArea} from "plotter.slint";
import {CT_historyPage} from "CT_history_page.slint";
//import {CT_tablePage} from "CT_table_page.slint";
import {SavePageAdapter ,SavePage} from "save_page.slint";
  
import {CT_mainPage,CT_tablePage} from "CT_main_page.slint";
export {SavePageAdapter ,SavePage,
    CT_historyPage,PlotArea,CT_tablePage, CT_mainPage,
    ControlsPage, TableViewPage, TableViewPageAdapter ,PlotterPage,
    PlotterPageAdapter}
